### ISSUE TITLE
Schematic for Wiring

### ISSUE THREAD

**Issue by s4b3rt0oth** [ultrara1n/DualCatFeeder#1]
Hi, I love your adaptation! Do you have a schematic for the wiring? Or better pictures?

I'm having a hard time deciphering where they ESP is wired and where the regulator is within the wiring. The PCB has a lot of information but I'm still a bit confused.

I'm also a tad confused where the group of connections on the PCB lead to on the arduino.

Thanks for any help you're able to provide!

**Comment by ultrara1n** [comment]
To be honest, this repository is not quite up to date.
I moved on to an ESP32, so the PCB is also outdated.
I'll gather all the changes and update the readme + include a schematic for the wiring.

**Comment by ultrara1n** [comment]
https://github.com/ultrara1n/dualcatfeeder-esp32#wiring
