### ISSUE TITLE
Lid for food-boxes missing

### ISSUE THREAD

**Issue by dominikgrimm** [ultrara1n/DualCatFeeder#2]
Hi,
first of all very nice project. 
I am currently printing the parts and was wondering if the lid for the food boxes is missing in the STL file folder?
Best wishes,
Dominik

**Comment by ultrara1n** [comment]
Hey Dominik,
sorry for my late response.
I've added the lid for the food boxes, but be aware that this solution is not optimal, as the holes for the lid are missing (i've designed the food boxes before the lid and forgot to add the holes...).
I've just drilled them with a drilling machine and used 5,0x16 screws to secure the lid:
![IMG_20210405_114544](https://user-images.githubusercontent.com/583246/113561340-b673a580-9604-11eb-99c5-c65d46880e35.jpg)

About the food box itself, there are currently some flaws. Some screws are not reachless unless you have very small hands. 
I have been putting off the redesign for quite a while, but i think the time has come to actually do it.
